// <auto-generated />
namespace Rocket6w6wH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CCPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CCPT));
        
        string IMigrationMetadata.Id
        {
            get { return "202412301556371_CCPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
