// <auto-generated />
namespace Rocket6w6wH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SAMACA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SAMACA));
        
        string IMigrationMetadata.Id
        {
            get { return "202412300643314_SAMACA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
