// <auto-generated />
namespace Rocket6w6wH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class storeaddtags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storeaddtags));
        
        string IMigrationMetadata.Id
        {
            get { return "202501020310567_storeaddtags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
